USE [master]
GO

/****** Object:  Database [WebTraderNewDB]    Script Date: 1/21/2018 7:26:42 AM ******/
CREATE DATABASE [WebTraderNewDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebTraderNewDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebTraderNewDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebTraderNewDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\WebTraderNewDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WebTraderNewDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebTraderNewDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebTraderNewDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebTraderNewDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebTraderNewDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebTraderNewDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebTraderNewDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebTraderNewDB] SET  MULTI_USER 
GO

ALTER DATABASE [WebTraderNewDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebTraderNewDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebTraderNewDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebTraderNewDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebTraderNewDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebTraderNewDB] SET QUERY_STORE = OFF
GO

USE [WebTraderNewDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [WebTraderNewDB] SET  READ_WRITE 
GO


